"""
Library to communicate with Samsung entertainment devices

Modules in this package:
    base: message parsing, constructing and basic communication class
    listener: receivers for events generated by the device
"""


from samsung.base import *


__version__ = '0.4.0'
__author__ = 'David Poisl <david@poisl.at>'