"""
Library to communicate with Samsung entertainment devices

Modules in this package:
    base: message parsing, constructing and basic communication class
    listener: receivers for events generated by the device
"""

__version__ = "0.2.0"
__author__ = "David Poisl <david@poisl.at>"

from samsung.base import *

