#!/usr/bin/python


from samsung import listener, base
import datetime
from time import sleep

base.set_logging(True)

def debug_print(message):
    """
    print messages from the server

    :param base.Message message: received message to print
    """
    print("--- %s ---\n%r\n" % (str(datetime.datetime.now()), message))


if __name__ == "__main__":
    from samsung import base
    base.set_logging(True)
    l = listener.ThreadReceiver("pyremote", "192.168.1.120")
    l.add_listener(debug_print)
    l.start()
    try:
        while True:
            sleep(1)
    except KeyboardInterrupt:
        l.stop()
